CREATE TABLE `USER` (
    `USER_ID` VARCHAR(16) BINARY NOT NULL	 COMMENT '用户内部识别ID',
    `LOGIN_ID` VARCHAR(64) BINARY 	 COMMENT '用户登录ID',
    `LOGIN_PASSWORD` VARCHAR(64) BINARY 	 COMMENT '用户登录密码',
    `USER_REAL_NAME` VARCHAR(64) BINARY 	 COMMENT '用户姓名',
    `MOBILE` VARCHAR(16) BINARY 	 COMMENT '用户手机',
    `MOBILE_BAK` VARCHAR(16) BINARY 	 COMMENT '用户备用手机',
    `IDENTITY_CARD` VARCHAR(32) BINARY 	 COMMENT '用户身份证号',
    `PASSPORT` VARCHAR(32) BINARY 	 COMMENT '用户护照号',
    `ADDRESS` VARCHAR(256) BINARY 	 COMMENT '用户地址',
    `EMAIL` VARCHAR(64) BINARY 	 COMMENT '用户邮箱',
    `EMAIL_BAK` VARCHAR(64) BINARY 	 COMMENT '用户备用邮箱',
    `LEVEL` INT(8) 	 COMMENT '用户等级',
    `STATUS` INT(2) 	 COMMENT '用户账户状态',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户表' ;
ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY ( USER_ID ) ;

CREATE TABLE `USER_WECHAT` (
    `USER_ID` VARCHAR(16) BINARY NOT NULL	 COMMENT '用户内部识别ID',
    `NICK_NAME` VARCHAR(128) BINARY NOT NULL	 COMMENT '用户昵称',
    `OPENID` VARCHAR(32) BINARY NOT NULL	 COMMENT '用户关联微信属性',
    `CITY` VARCHAR(64) BINARY 	 COMMENT '用户关联微信属性',
    `COUNTRY` VARCHAR(64) BINARY 	 COMMENT '用户关联微信属性',
    `HEADIMGURL` VARCHAR(512) BINARY 	 COMMENT '用户关联微信属性',
    `LANGUAGE` VARCHAR(64) BINARY 	 COMMENT '用户关联微信属性',
    `NICKNAME` VARCHAR(1024) BINARY 	 COMMENT '用户关联微信属性',
    `PROVINCE` VARCHAR(64) BINARY 	 COMMENT '用户关联微信属性',
    `SEX` VARCHAR(8) BINARY 	 COMMENT '用户关联微信属性',
    `UNIONID` VARCHAR(64) BINARY 	 COMMENT '用户关联微信属性',
    `PRIVILEGE` VARCHAR(512) BINARY 	 COMMENT '用户关联微信属性',
    `GROUPID` INT(8) 	 COMMENT '用户关联微信属性',
    `TAGID_LIST` VARCHAR(512) BINARY 	 COMMENT '用户关联微信属性',
    `SUBSCRIBE` INT(8) 	 COMMENT '用户关联微信属性',
	`SUBSCRIBE_TIME` TIMESTAMP 	NULL DEFAULT NULL COMMENT '用户关联微信属性',
    `CREATE_AUTHOR` VARCHAR(32) BINARY COMMENT '创建者',
    `CREATE_DATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_AUTHOR` VARCHAR(32) BINARY COMMENT '更新者',
    `UPDATE_DATETIME` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT '用户微信信息表' ;
ALTER TABLE `USER_WECHAT` ADD CONSTRAINT `PK_USER_WECHAT` PRIMARY KEY ( USER_ID ) ;